export const UPDATE_BASKET_REQUEST = 'UPDATE_BASKET_REQUEST';
export const UPDATE_BASKET_SUCCESS = 'UPDATE_BASKET_SUCCESS';
export const UPDATE_BASKET_FAILURE = 'UPDATE_BASKET_FAILURE';
export const ADDTO_BASKET_SUCCESS = 'ADDTO_BASKET_SUCCESS';
export const REMOVEFROM_BASKET_SUCCESS = 'REMOVEFROM_BASKET_SUCCESS';
